<a href="https://colab.research.google.com/github/bb20417/CE888/blob/main/lab4%20/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)
import matplotlib.pyplot as plt

In [4]:
user_ratings = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header=None )
print(user_ratings)

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

There's a column you need to remove because it doesn't contain ratings. Check the description of the dataset and figure out which one. Then drop it.

In [5]:
#dropping first column
user_ratings.drop(columns=[0],axis=1, inplace=True)

Check the dataset description to figure out which value you should replace with NaNs (the cells for which we don't have a rating). This is the test set.

In [6]:
user_ratings= user_ratings.replace(99.00, np.NaN)
user_ratings.head()

    1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 100 columns]

 Use pandas to find the best- and the worst-rated jokes

In [7]:
mean_rating = user_ratings.mean(axis=1)

In [8]:
top3_indices = np.argsort(mean_rating)

values = [mean_rating[i] for i in top3_indices]
print(values[:3],
values[-3:])

[-9.890694444444444, -9.798923076923078, -9.569166666666666] [9.0089, 9.122285714285713, 9.260800000000001]

In [9]:
print(top3_indices.head(),top3_indices.tail())

0    10643
1    21906
2    23458
3    23780
4     8709
dtype: int64 24978     1491
24979    14641
24980    23467
24981     1987
24982    22710
dtype: int64

Modify and use the helper function provided in the helper_function notebook (or create your own) to label 10% of the dataset cells that are not NaNs as 99. This is your **validation set**. Keep the the actual values of the cells so you can use them later (as done in the example of the helper_function notebook).

In [10]:
arr = user_ratings.values
print(arr.shape)

(24983, 100)

In [11]:
rated = np.where(~np.isnan(arr))
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)

In [12]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  #~np.isnan(a)
  new_data = orig.copy()
  rated = np.where(~np.isnan(arr))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [13]:
new_arr, idx = replace(arr, 0.1)

In [14]:
new_arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ..., 99.  , -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [15]:
arr[idx[0][0], idx[1][0]]

0.97

In [16]:
 new_arr[idx[0][0], idx[1][0]]

99.0

In [17]:
n_latent_factors = 2

#user_ratings = data.values
# Initialise as random values
latent_user_preferences = np.random.random((arr.shape[0], n_latent_factors))
latent_item_features = np.random.random((arr.shape[1], n_latent_factors))

In [ ]:
latent_user_preferences

In [ ]:
latent_item_features

In [20]:
arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [21]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = arr[user_id, item_id]
                if (~np.isnan(rating)) and rating!=99 :
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [22]:
num_iter = 100
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

Iteration 0/100:	MSE=26.155677
Iteration 10/100:	MSE=23.062581
Iteration 20/100:	MSE=21.223443
Iteration 30/100:	MSE=19.489777
Iteration 40/100:	MSE=17.572574
Iteration 50/100:	MSE=17.234044

KeyboardInterrupt: ignored

In [23]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-3.863, -4.429, -5.584, ..., -2.4  , -5.771, -2.35 ],
       [ 3.055,  3.325,  3.773, ...,  2.604,  3.763,  2.805],
       [ 5.859,  5.991,  5.841, ...,  6.528,  5.479,  7.437],
       ...,
       [-0.29 , -0.337, -0.436, ..., -0.162, -0.455, -0.151],
       [-0.902, -1.109, -1.577, ..., -0.259, -1.688, -0.145],
       [ 2.801,  2.77 ,  2.452, ...,  3.494,  2.196,  4.055]])

In [26]:
values = [zip(arr[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = user_ratings.columns

In [27]:
comparison_data

                                1    ...                          100
0      (-7.82, -3.8626859710313686)  ...   (nan, -2.3497021872171264)
1        (4.08, 3.0547338667569424)  ...    (1.07, 2.805013915299491)
2          (nan, 5.859000179252092)  ...     (nan, 7.436623558881537)
3          (nan, 2.522777972952849)  ...     (nan, 3.238861844919571)
4         (8.5, 2.9466967887472375)  ...     (1.6, 4.310287814705417)
...                             ...  ...                          ...
24978     (0.44, 2.257478811125793)  ...   (7.43, 3.8065221579872204)
24979    (9.13, 2.4838961630207814)  ...   (8.45, 1.5363499471396131)
24980    (nan, -0.2900847842436025)  ...  (nan, -0.15147321422077384)
24981     (nan, -0.901604489681896)  ...  (nan, -0.14504866528431096)
24982     (2.43, 2.800828054897238)  ...       (nan, 4.0554247249794)

[24983 rows x 100 columns]